### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: 'org.jetbrains.exposed.sql.Column io.github.dehuckakpyt.telegrambot.model.TelegramMessages.array(java.lang.String, org.jetbrains.exposed.sql.ColumnType, java.lang.Integer)'

### ISSUE THREAD

**Issue by HIlight3R** [DEHuckaKpyT/telegram-bot#11]
Hi, I get this error every time I try to run my project.

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.jetbrains.exposed.sql.Column io.github.dehuckakpyt.telegrambot.model.TelegramMessages.array(java.lang.String, org.jetbrains.exposed.sql.ColumnType, java.lang.Integer)'
	at io.github.dehuckakpyt.telegrambot.model.TelegramMessages.<clinit>(DatabaseTelegramMessage.kt:30)
	at io.github.dehuckakpyt.telegrambot.ext.source.SourceExtKt$inDatabase$4.invoke(SourceExt.kt:59)
	at io.github.dehuckakpyt.telegrambot.ext.source.SourceExtKt$inDatabase$4.invoke(SourceExt.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:236)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:283)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:291)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:282)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:291)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:174)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:162)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:161)
	at io.github.dehuckakpyt.telegrambot.ext.source.SourceExtKt.getInDatabase(SourceExt.kt:58)
	at io.github.hilight3r.kotodo.plugin.TelegramBotKt.configureTelegramBot$lambda$6$lambda$0(TelegramBot.kt:13)
	at io.github.dehuckakpyt.telegrambot.factory.TelegramBotFactory.createTelegramBotContext(TelegramBotFactory.kt:73)
	at io.github.dehuckakpyt.telegrambot.plugin.TelegramBotKt$TelegramBot$2.invoke(TelegramBot.kt:40)
	at io.github.dehuckakpyt.telegrambot.plugin.TelegramBotKt$TelegramBot$2.invoke(TelegramBot.kt:32)
	at io.ktor.server.application.CreatePluginUtilsKt.setupPlugin(CreatePluginUtils.kt:301)
	at io.ktor.server.application.CreatePluginUtilsKt.createPluginInstance(CreatePluginUtils.kt:270)
	at io.ktor.server.application.CreatePluginUtilsKt.access$createPluginInstance(CreatePluginUtils.kt:1)
	at io.ktor.server.application.CreatePluginUtilsKt$createApplicationPlugin$1.install(CreatePluginUtils.kt:52)
	at io.ktor.server.application.CreatePluginUtilsKt$createApplicationPlugin$1.install(CreatePluginUtils.kt:40)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
	at io.github.hilight3r.kotodo.plugin.TelegramBotKt.configureTelegramBot(TelegramBot.kt:12)
	at io.github.hilight3r.kotodo.ApplicationKt.module(Application.kt:14)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:188)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at io.ktor.server.engine.internal.CallableUtilsKt.callFunctionWithInjection(CallableUtils.kt:119)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:36)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:312)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:23)
	at io.github.hilight3r.kotodo.ApplicationKt.main(Application.kt:9)
```

I'm using:
- telegram-bot v0.11.0
- h2 v2.2.224
- exposed v0.55.0
- ktor v2.3.12
- koin v3.4.1

I tried changing exposed and h2 versions, but it didn't work.

Here are some snippets of my code, hopefully this helps:

`DatabaseConnection.kt`
```kotlin
package io.github.hilight3r.kotodo.plugin

import io.ktor.server.application.*
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.transaction
import org.koin.ktor.ext.inject
import javax.sql.DataSource

fun Application.configureDatabaseConnection() {
    val dataSource by inject<DataSource>()
    Database.connect(dataSource)

    transaction {
        SchemaUtils.createMissingTablesAndColumns()
    }
}
```

`TelegramBot.kt`
```kotlin
package io.github.hilight3r.kotodo.plugin

import io.github.dehuckakpyt.telegrambot.plugin.TelegramBot
import io.github.dehuckakpyt.telegrambot.source.callback.CallbackContentSource
import io.github.dehuckakpyt.telegrambot.source.chain.ChainSource
import io.github.dehuckakpyt.telegrambot.source.message.MessageSource
import io.github.dehuckakpyt.telegrambot.ext.source.inDatabase
import io.github.hilight3r.kotodo.handler.startCommand
import io.ktor.server.application.*

fun Application.configureTelegramBot() {
    install(TelegramBot) {
        messageSource = { MessageSource.inDatabase }

        receiving {
            longPolling {
                limit = 10
                timeout = 25
            }

            callbackContentSource = {
                CallbackContentSource.inDatabase(
                    maxCallbackContentsPerUser = 2
                )
            }
            chainSource = { ChainSource.inDatabase }

            handling {
                startCommand()
            }
        }
    }
}
```

**Comment by DEHuckaKpyT** [comment]
Hi. In about 10 hours, I'll be able to look at it(

**Comment by DEHuckaKpyT** [comment]
Hmm
I have no problems.. Application runs, bot responds to me. Maybe the wrong version of something?

I created a new blank project. My code:

`DependencyInjection.kt`
```kotlin
fun Application.configureDependencyInjection() {
    install(Koin) {
        slf4jLogger()
        modules(
//            defaultModule
        )
    }
}
```

`DatabaseConnection.kt`
```kotlin
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import io.ktor.server.application.*
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.transaction

fun Application.configureDatabase() {


    fun connect() {
        val hikariConfig = HikariConfig().apply {
            driverClassName = "org.h2.Driver"
            jdbcUrl = "jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
            maximumPoolSize = 64
            isAutoCommit = false
            transactionIsolation = "TRANSACTION_READ_COMMITTED"
            validate()
        }

        Database.connect(HikariDataSource(hikariConfig))
    }

    fun createTables() {
        transaction {
            SchemaUtils.createMissingTablesAndColumns()
        }
    }

    connect()
    createTables()
}
```

`TelegramBot.kt`
```kotlin
fun Application.configureTelegramBot() {
    install(TelegramBot) {
        messageSource = { MessageSource.inDatabase }

        receiving {
            longPolling {
                limit = 10
                timeout = 25
            }

            callbackContentSource = {
                CallbackContentSource.inDatabase(
                    maxCallbackContentsPerUser = 2
                )
            }
            chainSource = { ChainSource.inDatabase }

            handling {
                command("/start") {
                    sendMessage("Hello!")
                }
            }
        }
    }
}
```

`Application.kt`
```kotlin
import example.com.plugins.*
import io.github.dehuckakpyt.telegrambotexample.plugin.configureDatabase
import io.ktor.server.application.*

fun main(args: Array<String>) {
    io.ktor.server.netty.EngineMain.main(args)
}

fun Application.module() {
    configureDependencyInjection()
    configureDatabase()
    configureTelegramBot()
}
```

`build.gradle.kts`
```gradle
plugins {
    kotlin("jvm") version "1.8.22"
    id("com.google.devtools.ksp") version "1.8.22-1.0.11"
    id("io.ktor.plugin") version "2.3.12"
}

group = "example.com"
version = "0.0.1"

application {
    mainClass.set("io.ktor.server.netty.EngineMain")

    val isDevelopment: Boolean = project.ext.has("development")
    applicationDefaultJvmArgs = listOf("-Dio.ktor.development=$isDevelopment")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.ktor:ktor-server-core-jvm:2.3.12")
    implementation("io.ktor:ktor-server-netty-jvm:2.3.12")

    compileOnly("io.insert-koin:koin-annotations:1.2.2")
    ksp("io.insert-koin:koin-ksp-compiler:1.2.2")

    implementation("io.github.dehuckakpyt.telegrambot:telegram-bot-core:0.11.0")
    implementation("io.github.dehuckakpyt.telegrambot:telegram-bot-ktor:0.11.0")
    implementation("io.github.dehuckakpyt.telegrambot:telegram-bot-source-exposed:0.11.0")

    implementation("org.jetbrains.exposed:exposed-core:0.55.0")
    implementation("org.jetbrains.exposed:exposed-dao:0.55.0")
    implementation("org.jetbrains.exposed:exposed-jdbc:0.55.0")
    implementation("org.jetbrains.exposed:exposed-java-time:0.55.0")
    implementation("com.zaxxer:HikariCP:5.0.1")
    implementation("com.h2database:h2:2.2.224")
}
```

**Comment by HIlight3R** [comment]
I published my project. Can you take a look?
https://github.com/HIlight3R/KoToDo

**Comment by DEHuckaKpyT** [comment]
With this `build.gradle.kts ` and java 17 it works:

```kotlin
plugins {
    application
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.ktor)
    alias(libs.plugins.ksp)
}

group = "io.github.hilight3r"
version = "0.1.0-SNAPSHOT"

repositories {
    mavenLocal()
    mavenCentral()
    maven(uri("https://jitpack.io"))
}

dependencies {
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.exposed.core)
    implementation(libs.exposed.crypt)
    implementation(libs.exposed.dao)
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.kotlin.datetime)
    implementation(libs.exposed.json)
    implementation(libs.exposed.money)
    implementation(libs.h2)
    implementation(libs.hikari.cp)
    implementation(libs.koin.annotations)
    ksp(libs.koin.ksp.compiler)
    implementation(libs.telegram.bot.core)
    implementation(libs.telegram.bot.ktor)
    implementation(libs.telegram.bot.source.exposed)
//    implementation(libs.ktor.server.task.scheduling.core)
//    implementation(libs.ktor.server.task.scheduling.jdbc)
    implementation(libs.koin.ktor)
    implementation(libs.koin.logger.slf4j)
    implementation(libs.ktor.server.netty)
    implementation(libs.logback.classic)
    testImplementation(libs.ktor.server.test.host)
    testImplementation(libs.kotlin.test.junit)
}

sourceSets.main {
    java.srcDirs("build/generated/ksp/main/kotlin")
}

tasks.test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(17)
}

ksp {
    arg("KOIN_CONFIG_CHECK", "true")
}

application {
    mainClass = "io.github.hilight3r.kotodo.ApplicationKt"
}

tasks.withType<JavaExec> {
    file(".env").readLines().forEach {
        if (it.isNotEmpty() && !it.startsWith("#")) {
            val (key, value) = it.split("=", limit = 2)
            if (System.getenv(key) == null) environment(key, value)
        }
    }
}
```

But a had another problem with that dependency (without dependecy application works):
```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class io.ktor.client.engine.apache.ApacheEngine does not define or inherit an implementation of the resolved method 'abstract kotlinx.coroutines.CoroutineDispatcher getDispatcher()' of interface io.ktor.client.engine.HttpClientEngine.
	at io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:22)
	at io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.client.engine.HttpClientEngineBase.getCoroutineContext(HttpClientEngineBase.kt:21)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:90)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:84)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:43)
	at io.github.dehuckakpyt.telegrambot.api.client.TelegramApiClient.<init>(TelegramApiClient.kt:39)
	at io.github.dehuckakpyt.telegrambot.TelegramBotImpl.<init>(TelegramBotImpl.kt:138)
	at io.github.dehuckakpyt.telegrambot.factory.TelegramBotFactory.createTelegramBotContext(TelegramBotFactory.kt:74)
	at io.github.dehuckakpyt.telegrambot.plugin.TelegramBotKt$TelegramBot$2.invoke(TelegramBot.kt:40)
	at io.github.dehuckakpyt.telegrambot.plugin.TelegramBotKt$TelegramBot$2.invoke(TelegramBot.kt:32)
	at io.ktor.server.application.CreatePluginUtilsKt.setupPlugin(CreatePluginUtils.kt:301)
	at io.ktor.server.application.CreatePluginUtilsKt.createPluginInstance(CreatePluginUtils.kt:270)
	at io.ktor.server.application.CreatePluginUtilsKt.access$createPluginInstance(CreatePluginUtils.kt:1)
	at io.ktor.server.application.CreatePluginUtilsKt$createApplicationPlugin$1.install(CreatePluginUtils.kt:52)
	at io.ktor.server.application.CreatePluginUtilsKt$createApplicationPlugin$1.install(CreatePluginUtils.kt:40)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
	at io.github.hilight3r.kotodo.plugin.TelegramBotKt.configureTelegramBot(TelegramBot.kt:12)
	at io.github.hilight3r.kotodo.ApplicationKt.module(Application.kt:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:188)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at io.ktor.server.engine.internal.CallableUtilsKt.callFunctionWithInjection(CallableUtils.kt:119)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:36)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:312)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:23)
	at io.github.hilight3r.kotodo.ApplicationKt.main(Application.kt:8)
```

**Comment by DEHuckaKpyT** [comment]
I can try it with java 21 in a couple of days.

**Comment by DEHuckaKpyT** [comment]
I got the same problem by downgrading the version of Exposed to 0.49.0. Please make sure you install the correct version of Exposed (minimum 0.50.0). Maybe you have not reload dependencies?

![image](https://github.com/user-attachments/assets/cb7998b3-9613-48dc-97f8-03e9c61f2fa9)

**Comment by DEHuckaKpyT** [comment]
Have you any changes?

**Comment by HIlight3R** [comment]
Sorry for the long reply. Yes, I tried reloading dependencies.

Unfortunately, any changes in the version just replace one unsolvable error with another or even not help at all. I replaced the task library with db-scheduler and the problem went away.
